/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface JsonObjectValue {
    'jsonKey': String;
    'jsonVal': Object;
  }
  interface MyComponent {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
  interface WcCard {
    'height': string;
    'width': string;
  }
  interface WcJsonView {
    'data': Object;
  }
  interface WcTable {
    'delCol': (index: number) => void;
    'delRow': (index: number) => void;
    'editCell': (rowIndex: number, colIndex: number, value: any) => void;
    'insertCol': (destIndex: number) => void;
    'insertRow': (destIndex: number) => void;
    'tableData': [][];
  }
}

declare global {


  interface HTMLJsonObjectValueElement extends Components.JsonObjectValue, HTMLStencilElement {}
  var HTMLJsonObjectValueElement: {
    prototype: HTMLJsonObjectValueElement;
    new (): HTMLJsonObjectValueElement;
  };

  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLWcCardElement extends Components.WcCard, HTMLStencilElement {}
  var HTMLWcCardElement: {
    prototype: HTMLWcCardElement;
    new (): HTMLWcCardElement;
  };

  interface HTMLWcJsonViewElement extends Components.WcJsonView, HTMLStencilElement {}
  var HTMLWcJsonViewElement: {
    prototype: HTMLWcJsonViewElement;
    new (): HTMLWcJsonViewElement;
  };

  interface HTMLWcTableElement extends Components.WcTable, HTMLStencilElement {}
  var HTMLWcTableElement: {
    prototype: HTMLWcTableElement;
    new (): HTMLWcTableElement;
  };
  interface HTMLElementTagNameMap {
    'json-object-value': HTMLJsonObjectValueElement;
    'my-component': HTMLMyComponentElement;
    'wc-card': HTMLWcCardElement;
    'wc-json-view': HTMLWcJsonViewElement;
    'wc-table': HTMLWcTableElement;
  }
}

declare namespace LocalJSX {
  interface JsonObjectValue {
    'jsonKey'?: String;
    'jsonVal'?: Object;
  }
  interface MyComponent {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }
  interface WcCard {
    'height'?: string;
    'width'?: string;
  }
  interface WcJsonView {
    'data'?: Object;
  }
  interface WcTable {
    'delCol'?: (index: number) => void;
    'delRow'?: (index: number) => void;
    'editCell'?: (rowIndex: number, colIndex: number, value: any) => void;
    'insertCol'?: (destIndex: number) => void;
    'insertRow'?: (destIndex: number) => void;
    'tableData'?: [][];
  }

  interface IntrinsicElements {
    'json-object-value': JsonObjectValue;
    'my-component': MyComponent;
    'wc-card': WcCard;
    'wc-json-view': WcJsonView;
    'wc-table': WcTable;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'json-object-value': LocalJSX.JsonObjectValue & JSXBase.HTMLAttributes<HTMLJsonObjectValueElement>;
      'my-component': LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
      'wc-card': LocalJSX.WcCard & JSXBase.HTMLAttributes<HTMLWcCardElement>;
      'wc-json-view': LocalJSX.WcJsonView & JSXBase.HTMLAttributes<HTMLWcJsonViewElement>;
      'wc-table': LocalJSX.WcTable & JSXBase.HTMLAttributes<HTMLWcTableElement>;
    }
  }
}


